<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menuItems = [
            [
                'id' => 1,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'mingcute:shop-fill',
                'label' => 'Магазин',
                'href' => null,
                'description' => 'Администрирование товаров магазина',
                'order' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-30 18:43:13',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 2,
                'page_id' => 3,
                'parent_id' => null,
                'icon' => 'ic:round-settings',
                'label' => 'Настройки сайта',
                'href' => null,
                'description' => 'Настройки основного сайта',
                'order' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-30 18:43:13',
                'updated_at' => '2025-09-15 03:35:11',
            ],
            [
                'id' => 3,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'line-md:cog-loop',
                'label' => 'Настройки',
                'href' => null,
                'description' => 'Редактирование значений переменных системы',
                'order' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-30 18:43:13',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 5,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'fluent:braces-variable-24-filled',
                'label' => 'Переменные',
                'href' => 'variables',
                'description' => 'Редактирование переменных сайта',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-08-30 19:34:34',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 6,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'carbon:punctuation-check',
                'label' => 'Разделы админки',
                'href' => 'pages',
                'description' => 'Редактирование разделов админки',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-08-30 20:15:28',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 7,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'carbon:collapse-categories',
                'label' => 'Категории',
                'href' => 'categories',
                'description' => 'Редактирование категорий товаров',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-09-02 08:04:07',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 8,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'eos-icons:role-binding-outlined',
                'label' => 'Роли',
                'href' => 'roles',
                'description' => 'Администрирование ролей пользователей',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-02 08:52:08',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 9,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'carbon:ibm-watson-knowledge-catalog',
                'label' => 'Каталог товаров',
                'href' => 'goods',
                'description' => 'Администрирование каталога товаров',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-02 11:00:52',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 10,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'mynaui:brand-pocket',
                'label' => 'Бренды',
                'href' => 'brands',
                'description' => 'Администрирование брендов',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-09-02 11:06:21',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 11,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'carbon:ibm-watson-orders',
                'label' => 'Заказы',
                'href' => 'orders',
                'description' => 'Администрирование заказов',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-09-02 11:07:47',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 12,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'flowbite:users-solid',
                'label' => 'Пользователи',
                'href' => 'users',
                'description' => 'Администрирование пользователей сайта',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-09-03 11:22:04',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 13,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'heroicons-outline:template',
                'label' => 'Шаблоны сайта',
                'href' => 'templates',
                'description' => 'Редактор шаблонов основного сайта',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-09-03 11:25:43',
                'updated_at' => '2025-09-03 14:00:47',
            ],
            [
                'id' => 14,
                'page_id' => 1,
                'parent_id' => null,
                'icon' => 'gg:menu-round',
                'label' => 'Редактор меню',
                'href' => 'sitemenu',
                'description' => 'Редактирование меню основного сайта',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-09-03 14:00:26',
                'updated_at' => '2025-09-03 14:16:51',
            ],
            [
                'id' => 15,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'line-md:download-loop',
                'label' => 'Импорт товаров',
                'href' => 'goods/import',
                'description' => 'Импорт товаров из файлов или Google Sheets',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-07 04:46:18',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 16,
                'page_id' => 3,
                'parent_id' => null,
                'icon' => 'ion:location-sharp',
                'label' => 'Контакты',
                'href' => 'contacts',
                'description' => 'Редактирование контактов',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-15 03:35:06',
                'updated_at' => '2025-09-15 03:35:11',
            ],
            [
                'id' => 17,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'si:phone-callback-fill',
                'label' => 'Сообщения на сайте',
                'href' => 'callback',
                'description' => 'Заказ обратного звонка и сообщения на сайте',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-15 08:33:22',
                'updated_at' => '2025-09-15 08:33:31',
            ],


            [
                'id' => 18,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'hugeicons:delivery-truck-01',
                'label' => 'Доставка',
                'href' => 'delivery',
                'description' => 'Управления методами доставки',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-15 08:33:22',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 19,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'hugeicons:payment-02',
                'label' => 'Оплата',
                'href' => 'payment',
                'description' => 'Управление методами оплаты',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-15 08:33:22',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 20,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'lucide:badge-russian-ruble',
                'label' => 'Бонусная система',
                'href' => 'bonus',
                'description' => 'Управление бонусной системой',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-15 08:33:22',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 21,
                'page_id' => 2,
                'parent_id' => null,
                'icon' => 'arcticons:cdek',
                'label' => 'СДЕК',
                'href' => 'cdek',
                'description' => 'Настройки интеграции СДЕК',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-15 08:33:22',
                'updated_at' => '2025-09-15 08:33:31',
            ],
            [
                'id' => 22,
                'page_id' => 3,
                'parent_id' => null,
                'icon' => 'mdi:page-layout-header-footer',
                'label' => 'Конструктор страниц',
                'href' => 'constructor',
                'description' => 'Визуальный конструктор страниц',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-01-20 10:00:00',
                'updated_at' => '2026-01-20 10:00:00',
            ],
            [
                'id' => 23,
                'page_id' => 3,
                'parent_id' => null,
                'icon' => 'mdi:file-document-multiple',
                'label' => 'Страницы',
                'href' => 'constructor-pages',
                'description' => 'Управление страницами конструктора',
                'order' => 3,
                'is_active' => 1, // Активно в меню для тестирования
                'created_at' => '2026-01-20 10:00:00',
                'updated_at' => '2026-01-20 10:00:00',
            ],
        ];

        foreach ($menuItems as $item) {
            DB::table('admin_menu_items')->updateOrInsert(
                ['id' => $item['id']],
                $item
            );
        }
    }
}














