<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'id' => 1,
                'key' => 'site_name',
                'name' => 'Название сайта',
                'value' => 'SKATE & SNOW',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Название сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-08-30 18:43:14',
                'updated_at' => '2025-09-15 10:31:17',
            ],
            [
                'id' => 2,
                'key' => 'site_description',
                'name' => 'Описание сайта (description)',
                'value' => 'Интернет-магазин для активного спорта и отдыха!',
                'type' => 'text',
                'group' => 'general',
                'description' => 'Описание сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-08-30 18:43:14',
                'updated_at' => '2025-09-15 10:31:15',
            ],
            [
                'id' => 3,
                'key' => 'site_logo',
                'name' => 'Логотип сайта',
                'value' => 'images\\settings\\setting_3_1756748468.png',
                'type' => 'image',
                'group' => 'general',
                'description' => 'Логотип в шапке сайта и везде, где необходимо',
                'image_width' => 400,
                'image_height' => 400,
                'created_at' => '2025-08-30 18:43:14',
                'updated_at' => '2025-08-31 06:16:53',
            ],
            [
                'id' => 4,
                'key' => 'main_site',
                'name' => 'URL адрес сайта',
                'value' => 'http://localhost:3000',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Адрес основного сайта',
                'image_width' => 200,
                'image_height' => 200,
                'created_at' => '2025-08-30 18:43:14',
                'updated_at' => '2025-09-03 07:50:38',
            ],
            [
                'id' => 5,
                'key' => 'quick_login',
                'name' => 'Быстрый вход',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'general',
                'description' => 'Отключает кнопку быстрого входа под тестовым пользователем при аутентификации',
                'image_width' => 200,
                'image_height' => 200,
                'created_at' => '2025-08-30 18:43:14',
                'updated_at' => '2025-09-05 11:12:15',
            ],
            [
                'id' => 6,
                'key' => 'admin_name',
                'name' => 'Название админки',
                'value' => 'Skate&Snow CMS',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Значение переменной - в заголовках админки',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-08-30 19:41:04',
                'updated_at' => '2025-08-31 04:43:30',
            ],
            [
                'id' => 8,
                'key' => 'site_favicon',
                'name' => 'Иконка сайта',
                'value' => 'images/settings/setting_8_1756812882.png',
                'type' => 'image',
                'group' => 'general',
                'description' => 'Иконка сайта, отображаемая на сайте и в админке',
                'image_width' => 32,
                'image_height' => 32,
                'created_at' => '2025-08-30 20:00:22',
                'updated_at' => '2025-09-02 08:34:42',
            ],
            [
                'id' => 9,
                'key' => 'shop_category_img_width',
                'name' => 'Ширина изображения в каталоге',
                'value' => '350',
                'type' => 'number',
                'group' => 'shop',
                'description' => 'Задает ширину, к которой приводится изображение к каталоге товаров, px',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-02 08:36:15',
                'updated_at' => '2025-09-02 08:38:01',
            ],
            [
                'id' => 10,
                'key' => 'shop_category_img_height',
                'name' => 'Высота изображения в каталоге товаров',
                'value' => '350',
                'type' => 'number',
                'group' => 'shop',
                'description' => 'Задает высоту, к которой приводится изображение к каталоге товаров, px',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-02 08:37:31',
                'updated_at' => '2025-09-02 08:38:01',
            ],
            [
                'id' => 12,
                'key' => 'site_color1',
                'name' => 'Цвет сайта 1',
                'value' => '#000000',
                'type' => 'color',
                'group' => 'site',
                'description' => 'Стиль цвета сайта 1',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-03 18:38:01',
                'updated_at' => '2025-09-03 19:54:43',
            ],
            [
                'id' => 13,
                'key' => 'site_color2',
                'name' => 'Цвет сайта 2',
                'value' => '#EAB308',
                'type' => 'color',
                'group' => 'site',
                'description' => 'Цвет tailwind сайта 2',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-03 18:41:13',
                'updated_at' => '2025-09-15 08:56:53',
            ],
            [
                'id' => 14,
                'key' => 'site_preloader_color',
                'name' => 'Цвет прелоадера',
                'value' => '#000000',
                'type' => 'color',
                'group' => 'site',
                'description' => 'Цвет прелоадера главного сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-03 20:12:14',
                'updated_at' => '2025-09-03 20:55:00',
            ],
            [
                'id' => 15,
                'key' => 'site_login_google',
                'name' => 'Авторизация Google',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'site',
                'description' => 'Включает авторизацию на сайте через сервис Google',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-05 17:05:01',
                'updated_at' => '2025-09-05 17:25:04',
            ],
            [
                'id' => 16,
                'key' => 'site_login_yandex',
                'name' => 'Авторизация Яндекс',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'site',
                'description' => 'Включает авторизацию на сайте через сервис Яндекс',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-05 17:05:52',
                'updated_at' => '2025-09-05 17:16:52',
            ],
            [
                'id' => 17,
                'key' => 'site_login_vk',
                'name' => 'Авторизация ВКонтакте',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'site',
                'description' => 'Включает авторизацию на сайте через сервис Вконтакте',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-05 17:06:32',
                'updated_at' => '2025-09-05 17:25:04',
            ],
            [
                'id' => 18,
                'key' => 'site_login_phone',
                'name' => 'Авторизация через звонок',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'site',
                'description' => 'Включает авторизацию на сайте через телефонный звонок',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-05 17:07:30',
                'updated_at' => '2025-09-05 17:24:33',
            ],
            [
                'id' => 19,
                'key' => 'shop_good_width',
                'name' => 'Ширина изображения товара',
                'value' => '500',
                'type' => 'number',
                'group' => 'shop',
                'description' => 'Ширина изображения товара, px',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-06 09:43:35',
                'updated_at' => '2025-09-06 09:45:25',
            ],
            [
                'id' => 20,
                'key' => 'shop_good_height',
                'name' => 'Высота изображения товара',
                'value' => '500',
                'type' => 'number',
                'group' => 'shop',
                'description' => 'Высота изображения товара, px',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-06 09:44:47',
                'updated_at' => '2025-09-06 09:45:24',
            ],
            [
                'id' => 21,
                'key' => 'shop_catalog_path',
                'name' => 'Путь к каталогу товаров',
                'value' => 'catalog',
                'type' => 'string',
                'group' => 'shop',
                'description' => 'Папка, где располагается каталог товаров',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-13 04:32:23',
                'updated_at' => '2025-09-13 13:48:30',
            ],
            [
                'id' => 22,
                'key' => 'site_google_font',
                'name' => 'Шрифт GoogleFont',
                'value' => 'Oswald',
                'type' => 'string',
                'group' => 'site',
                'description' => 'Название шрифта Google Fonts для сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-13 21:35:25',
                'updated_at' => '2025-09-13 21:43:29',
            ],
            [
                'id' => 23,
                'key' => 'site_contact_page',
                'name' => 'Адрес страницы контактов',
                'value' => 'contacts2',
                'type' => 'string',
                'group' => 'site',
                'description' => 'Адрес страницы контактов без / в начале',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-15 05:50:29',
                'updated_at' => '2025-09-15 05:55:07',
            ],
            [
                'id' => 24,
                'key' => 'site_show_callback',
                'name' => 'Форма обратного звонка',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'site',
                'description' => 'Показывать форму обратного звонка',
                'image_width' => null,
                'image_height' => null,
                'created_at' => '2025-09-15 05:51:43',
                'updated_at' => '2025-09-15 08:54:12',
            ],
            [
                'id' => 25,
                'key' => 'site_logo_negative',
                'name' => 'Логотип сайта в инверсии',
                'value' => 'images/settings/setting_25_1757967941.png',
                'type' => 'image',
                'group' => 'general',
                'description' => null,
                'image_width' => 400,
                'image_height' => 400,
                'created_at' => '2025-09-15 17:24:08',
                'updated_at' => '2025-09-15 17:25:41',
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['id' => $setting['id']],
                $setting
            );
        }
    }
}







