<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'key' => 'site_name',
                'name' => 'Название сайта',
                'value' => 'Skate and Snow',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Название сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'admin_name',
                'name' => 'Название админ-панели',
                'value' => 'Ваше значение',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Название админ-панели',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_description',
                'name' => 'Описание сайта',
                'value' => 'Магазин и аренда оборудования для сноуборда и скейтборда',
                'type' => 'text',
                'group' => 'general',
                'description' => 'Описание сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_logo',
                'name' => 'Логотип сайта',
                'value' => 'public/logo-ss-big.png',
                'type' => 'image',
                'group' => 'general',
                'description' => 'Логотип сайта для использования в SEO и интерфейсе',
                'image_width' => 1200,
                'image_height' => 630,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'admin_email',
                'name' => 'Email администратора',
                'value' => 'admin@skateandsnow.ru',
                'type' => 'email',
                'group' => 'admin',
                'description' => 'Email администратора',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'quick_login',
                'name' => 'Быстрый вход',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'admin',
                'description' => 'Показывать кнопку быстрого входа для администратора',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_avatar_width',
                'name' => 'Ширина аватара по умолчанию',
                'value' => '200',
                'type' => 'integer',
                'group' => 'images',
                'description' => 'Ширина аватара по умолчанию',
                'image_width' => 200,
                'image_height' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'default_avatar_height',
                'name' => 'Высота аватара по умолчанию',
                'value' => '200',
                'type' => 'integer',
                'group' => 'images',
                'description' => 'Высота аватара по умолчанию',
                'image_width' => 200,
                'image_height' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'footer_start_year',
                'name' => 'Год начала копирайта',
                'value' => '2024',
                'type' => 'string',
                'group' => 'footer',
                'description' => 'Год начала копирайта для футера',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'footer_copy',
                'name' => 'Текст копирайта',
                'value' => 'SkateAndSnow',
                'type' => 'string',
                'group' => 'footer',
                'description' => 'Текст копирайта для футера',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'footer_copy_link',
                'name' => 'Ссылка копирайта',
                'value' => 'https://skateandsnow.ru',
                'type' => 'string',
                'group' => 'footer',
                'description' => 'Ссылка для текста копирайта в футере',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // SEO настройки
            [
                'key' => 'meta_title',
                'name' => 'Meta заголовок',
                'value' => 'Skate and Snow - Магазин оборудования для скейтбординга и сноубординга',
                'type' => 'string',
                'group' => 'seo',
                'description' => 'Основной meta заголовок сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_description',
                'name' => 'Meta описание',
                'value' => 'Качественное оборудование для скейтбординга и сноубординга. Быстрая доставка по всей России, гарантия качества, экспертная поддержка. Широкий ассортимент досок, креплений, ботинок и аксессуаров.',
                'type' => 'text',
                'group' => 'seo',
                'description' => 'Основное meta описание сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_image',
                'name' => 'Meta изображение',
                'value' => 'public/logo-ss-big.png',
                'type' => 'image',
                'group' => 'seo',
                'description' => 'Основное изображение для социальных сетей',
                'image_width' => 1200,
                'image_height' => 630,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_keywords',
                'name' => 'Meta ключевые слова',
                'value' => 'скейтборд, сноуборд, магазин, оборудование, доставка, крепления, ботинки, доски, аксессуары',
                'type' => 'text',
                'group' => 'seo',
                'description' => 'Ключевые слова для SEO',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_preloader_color',
                'name' => 'Цвет прелоадера сайта',
                'value' => '#3B82F6',
                'type' => 'color',
                'group' => 'general',
                'description' => 'Цвет спиннера прелоадера для всех страниц сайта',
                'image_width' => null,
                'image_height' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->insert($setting);
        }
    }
}
