<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@skateandsnow.ru',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => 'images/users/avatar_1_1756810643.png',
                'avatar_url' => null,
                'email_verified_at' => '2025-08-30 18:43:13',
                'password' => '$2y$12$x6IWINE9FAyoXGp/sKUeBeA18fRXNCQWKeteWu1pGYCyA9opc6WdG',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-08-30 18:43:13',
                'updated_at' => '2025-09-02 07:57:23',
                'phone' => null,
                'phone_verified_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Менеджер',
                'email' => 'manager@kirhtarg.ru',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => 'images/users/avatar_2_1757080107.png',
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 15:49:15',
                'password' => '$2y$12$GMPE5os5rPrPsj1tuyJNQODSnxIJgNxVVX8F3HPMx5VhxzIFIBC7.',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-02 08:50:17',
                'updated_at' => '2025-09-05 15:49:15',
                'phone' => null,
                'phone_verified_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Test',
                'email' => 'test@test.ru',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => '323232',
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 13:28:36',
                'password' => '$2y$12$vY5TtxU8YP20vOfIyt0i6O2WEIU493ZvsQ2dx9piarNNQUTSlXbjy',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-02 08:55:51',
                'updated_at' => '2025-09-05 13:28:36',
                'phone' => null,
                'phone_verified_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Hoy',
                'email' => 'durshlag@mail.ru',
                'google_id' => null,
                'vk_id' => '333',
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 13:28:39',
                'password' => '$2y$12$DrkersPtffsbv6Vzec8e8OvzQE.ySEab3AF2KWAUqmkAlleEg1uH.',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-03 18:59:05',
                'updated_at' => '2025-09-05 13:28:39',
                'phone' => null,
                'phone_verified_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'ппп',
                'email' => 'durshlag2@mail.ru',
                'google_id' => '1234',
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$TyexwNUVBeXISmn7cu8EteRvB9qlTV7TpvlcY83bb4swzVSsPKsUy',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-03 19:02:33',
                'updated_at' => '2025-09-05 13:28:41',
                'phone' => null,
                'phone_verified_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Пользователь 4575',
                'email' => 'phone_+79991234575@temp.local',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 13:19:58',
                'password' => '$2y$12$NANqTOInAx1xcalh9v12FeJcIX9eLokkMKoLBYzvWyd3DPMTT0tG6',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-05 06:52:33',
                'updated_at' => '2025-09-05 13:19:58',
                'phone' => '+79991234575',
                'phone_verified_at' => '2025-09-05 09:52:33',
            ],
            [
                'id' => 11,
                'name' => 'Пользователь 4576',
                'email' => 'phone_+79991234576@temp.local',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 13:18:25',
                'password' => '$2y$12$eQnaeysOZwfRTwaqlv9I3O8lBSjJgdP/mc7ZkKQiGd4Vho0Qxrpu.',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-05 06:53:20',
                'updated_at' => '2025-09-05 13:18:25',
                'phone' => '+79991234576',
                'phone_verified_at' => '2025-09-05 09:53:20',
            ],
            [
                'id' => 12,
                'name' => '+79991234579',
                'email' => 'phone_+79991234579@temp.local',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => '/ph.png',
                'email_verified_at' => '2025-09-05 13:18:06',
                'password' => '$2y$12$axHV0kbWxLAMSX.Xba2edeFW.zcr64dObHCX8Cp.ehs/lEUl3RF56',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-05 06:58:57',
                'updated_at' => '2025-09-05 13:18:06',
                'phone' => '+79991234579',
                'phone_verified_at' => '2025-09-05 09:58:57',
            ],
            [
                'id' => 13,
                'name' => '+79956003778',
                'email' => 'phone_+79956003778@temp.local',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => '/ph.png',
                'email_verified_at' => '2025-09-05 13:32:54',
                'password' => '$2y$12$2hTNXXjKjlEWSVO0mzoJiuokCH55dL7x2j0K0v9o1qY5u/S5lTnUu',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-05 08:49:26',
                'updated_at' => '2025-09-05 13:32:54',
                'phone' => '+79956003778',
                'phone_verified_at' => '2025-09-05 11:49:26',
            ],
            [
                'id' => 19,
                'name' => 'ккк',
                'email' => 'wer@wer.ru',
                'google_id' => null,
                'vk_id' => null,
                'yandex_id' => null,
                'avatar' => null,
                'avatar_url' => null,
                'email_verified_at' => '2025-09-05 16:28:05',
                'password' => '$2y$12$xyIq7iRYa0tWfjst9/qow.8ByU/.AW0dxwmmbW7x5Jw8gT.ruQdgK',
                'is_active' => 1,
                'remember_token' => null,
                'created_at' => '2025-09-05 16:26:28',
                'updated_at' => '2025-09-05 16:28:05',
                'phone' => null,
                'phone_verified_at' => null,
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->updateOrInsert(
                ['id' => $user['id']],
                $user
            );
        }
    }
}


