[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /path/to/api.ss.ru/artisan queue:work --tries=3 --timeout=3600 --sleep=3 --max-jobs=1000
directory=/path/to/api.ss.ru
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/path/to/api.ss.ru/storage/logs/queue-worker.log